name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-version: 1.3.243

      - name: Install SDL2
        shell: powershell
        run: |
          mkdir -p external
          cd external
          $SDL2_VERSION = "2.28.5"
          Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-$SDL2_VERSION/SDL2-devel-$SDL2_VERSION-VC.zip" -OutFile "SDL2-devel-$SDL2_VERSION-VC.zip"
          Expand-Archive "SDL2-devel-$SDL2_VERSION-VC.zip" -DestinationPath .
          Move-Item "SDL2-$SDL2_VERSION" SDL2
          cd ..

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --output-on-failure

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy clang-format

      - name: Run clang-format
        run: |
          find src include -iname *.cpp -o -iname *.h -o -iname *.hpp | xargs clang-format --dry-run --Werror
